---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.masters | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
    - name: Add tskey to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: tskey-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install first master
  hosts: '{{ groups.masters[0] | default([]) }}'
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-install-nodes-first.ansible.yaml
    - name: Create cluster facts
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-data-facts-create.ansible.yaml
- name: Install others masters
  hosts: "{{ groups.masters[1:] | default([]) }}"
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-install-nodes-others.ansible.yaml
- name: Fix cluster configs
  hosts: "{{ groups.masters | default([]) }}"
  become: true
  tasks:
    - name: Fix config
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-data-fix-location.ansible.yaml
