---
# =================
# --- HOSTVARS ---
# =================
- name: Fix host_vars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Fetch ssh key
      when: 'not skip_hostvars_fix_ssh_key | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-fetch.ansible.yaml
    - name: Add sudo to host_vars
      when: 'not skip_hostvars_fix_sudo | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Uninstall workers
  hosts: '{{ groups.workers | default([]) }}'
  become: true
  tasks:
    - name: Uninstall nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-worker-uninstall.ansible.yaml
- name: Uninstall masters
  hosts: '{{ groups.masters | default([]) }}'
  become: true
  tasks:
    - name: Uninstall masters
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-uninstall.ansible.yaml
