---
# =================
# --- HOST_VARS ---
# =================
- name: Fix host_vars for nodes
  hosts: '{{ groups.all | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
#- name: Install private registry
#  hosts: "{{ groups.all | default([]) }}"
#  become: true
#  tasks:
#    - name: Install registry
#      ansible.builtin.include_role:
#        name: k8s
#        tasks_from: k3s-all-install-private-registry.ansible.yaml
- name: Restart k3s nodes
  hosts: "{{ groups.nodes | default([]) }}"
  become: true
  tasks:
    - name: Restart nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-node-restart.ansible.yaml
