---
# ================
# --- PLAYBOOK ---
# ================
- name: Label nodes
  hosts: '{{ groups.masters[0] | default ([]) }}'
  tasks:
    - name: Label nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-all-label.ansible.yaml
