---
# ================
# --- PLAYBOOK ---
# ================
- name: Label nodes
  hosts: '{{ groups.nodes | default ([]) }}'
  tasks:
    - name: Fetch ssh key and use
      when: 'not skip_hostvars_fix_ssh_key_fetch | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-fetch-and-use.ansible.yaml
    - name: Label nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-nodes-label.ansible.yaml
