---
# =================
# --- HOST_VARS ---
# =================
- name: Fix host_vars
  hosts: '{{ groups.masters | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
    - name: Add tskey to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: tskey-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install first master
  hosts: '{{ groups.masters[0] | default([]) }}'
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-install-first.ansible.yaml
- name: Get cluster data
  hosts: '{{ groups.masters[0] | default([]) }}'
  become: true
  tasks:
    - name: Get cluster data
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-data.ansible.yaml
- name: Install other masters
  hosts: "{{ groups.masters[1:] | default([]) }}"
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-install-others.ansible.yaml
- name: Fix cluster configs
  hosts: "{{ groups.masters | default([]) }}"
  become: true
  tasks:
    - name: Fix config
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-config-fix.ansible.yaml
- name: Download cluster config
  hosts: '{{ groups.masters[0] | default([]) }}'
  become: true
  tasks:
    - name: Download cluster config
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-download.ansible.yaml
