---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars for first master
  hosts: '{{ groups.masters[0] | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
- name: Fix hostvars for workers
  hosts: '{{ groups.workers | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
    - name: Add tskey to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: tskey-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Create cluster facts
  hosts: '{{ groups.masters[0] | default([]) }}'
  become: true
  tasks:
    - name: Create cluster facts
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-master-cluster-data-facts-create.ansible.yaml
- name: Install k3s on workers
  hosts: "{{ groups.workers | default([]) }}"
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-worker-install.ansible.yaml
