---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Fetch ssh key
      when: 'not skip_hostvars_fix_ssh_key | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-fetch.ansible.yaml
    - name: Add sudo to hostvars
      when: 'not skip_hostvars_fix_sudo | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install private registry
  hosts: "{{ groups.nodes | default([]) }}"
  become: true
  tasks:
    - name: Install registry
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-nodes-install-private-registry.ansible.yaml
- name: Restart k3s
  hosts: "{{ groups.nodes | default([]) }}"
  become: true
  tasks:
    - name: Restart k3s on nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-nodes-restart.ansible.yaml
