---
# ================
# --- PLAYBOOK ---
# ================
- name: Label nodes
  hosts: '{{ groups.nodes | default ([]) }}'
  tasks:
    - name: Label nodes
      ansible.builtin.include_role:
        name: k8s
        tasks_from: k3s-nodes-label.ansible.yaml
