---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Uninstall longhorn
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Uninstall longhorn
      ansible.builtin.include_role:
        name: k8s
        tasks_from: longhorn-uninstall.ansible.yaml
