---
- name: Copy registry-tls.crt
  ansible.builtin.copy:
    src: registry-tls.crt
    dest: /usr/local/share/ca-certificates/registry-tls.crt
    mode: u=rw,g=,o=
- name: Copy registry-tls.key
  ansible.builtin.copy:
    src: registry-tls.key
    dest: /usr/local/share/ca-certificates/registry-tls.key
    mode: u=rw,g=,o=
- name: Copy kubernetes.ca
  ansible.builtin.copy:
    src: kubernetes.ca
    dest: /usr/local/share/ca-certificates/kubernetes.ca
    mode: u=rw,g=,o=
- name: Create k3s folder
  ansible.builtin.file:
    path: /etc/rancher/k3s
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
- name: Copy registries.yaml
  ansible.builtin.copy:
    src: registries.yaml
    dest: /etc/rancher/k3s/registries.yaml
    mode: u=rw,g=,o=
