---
- name: Get node's IPv4 # noqa command-instead-of-shell
  ansible.builtin.shell: tailscale ip -4
  register: node_ip_v4
  changed_when: node_ip_v4.rc != 0
- name: Get node's IPv6 # noqa command-instead-of-shell
  ansible.builtin.shell: tailscale ip -6
  register: node_ip_v6
  changed_when: node_ip_v6.rc != 0
- name: Install k3s # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >- 
    curl -sfL https://get.k3s.io | 
    K3S_NODE_NAME="{{ inventory_hostname }}" 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    INSTALL_K3S_EXEC="
      server 
      --node-ip={{ node_ip_v4.stdout + ',' + node_ip_v6.stdout }} 
      --advertise-address={{ node_ip_v4.stdout }} 
      --vpn-auth="name=tailscale,joinKey={{ ts_key }}" 
      --disable=traefik 
      --disable=servicelb 
      --secrets-encryption 
      --cluster-cidr=10.42.0.0/16,2001:cafe:42:0::/56 
      --service-cidr=10.43.0.0/16,2001:cafe:42:1::/112 
      --cluster-init 
    " sh -s -
  register: k3s_install
  changed_when: k3s_install.rc != 0
