---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: true
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install packages and enable kernel modules
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Update apt
      ansible.builtin.include_role:
        name: linux
        tasks_from: apt-update.ansible.yaml
    - name: Install packages
      ansible.builtin.include_role:
        name: linux
        tasks_from: apt-install.ansible.yaml
    - name: Enable kernel modules
      ansible.builtin.include_role:
        name: linux
        tasks_from: kernel-modules-enable.ansible.yaml
