---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      when: 'not skip_hostvars_fix_sudo | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Refresh packages
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Update apt
      ansible.builtin.include_role:
        name: linux
        tasks_from: apt-update.ansible.yaml
    - name: Install packages
      ansible.builtin.include_role:
        name: linux
        tasks_from: apt-install.ansible.yaml
