---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Fix sshd config
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Fix sshd config
      ansible.builtin.include_role:
        name: linux
        tasks_from: ssh-config-fix.ansible.yaml
