---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Fetch ssh key
      when: 'not skip_hostvars_fix_ssh_key | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-fetch.ansible.yaml
    - name: Add ssh_pass to hostvars
      when: 'not skip_hostvars_fix_ssh_pass | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-password-add.ansible.yaml
    - name: Add sudo to hostvars
      when: 'not skip_hostvars_fix_sudo | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
    - name: Add tskey to hostvars
      when: 'not skip_hostvars_fix_tskey | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: tskey-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install tailscale
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Refresh packages
      ansible.builtin.include_role:
        name: linux
        tasks_from: apt-update.ansible.yaml
    - name: Install tailscale
      ansible.builtin.include_role:
        name: linux
        tasks_from: tailscale-install.ansible.yaml
