---
# =================
# --- HOST_VARS ---
# =================
- name: Fix host_vars
  hosts: '{{ groups.new }}'
  gather_facts: false
  tasks:
    - name: Add passwords to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: users-passwords-add.ansible.yaml
    - name: Add ssh_key to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-add.ansible.yaml
    - name: Add ssh_pass to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-password-add.ansible.yaml
    - name: Add sudo to host_vars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Init user
  hosts: '{{ groups.new }}'
  become: true
  tasks:
    - name: Create user
      ansible.builtin.include_role:
        name: linux
        tasks_from: user-add.ansible.yaml
    - name: Fix passwords
      ansible.builtin.include_role:
        name: linux
        tasks_from: passwords-update.ansible.yaml
- name: Copy ssh key
  hosts: '{{ groups.new }}'
  tasks:
    - name: Overwrite ssh key
      ansible.builtin.include_role:
        name: linux
        tasks_from: ssh-key-overwrite.ansible.yaml
