---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Add sudo to hostvars
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Install zsh and plugins
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Download all github sources
      ansible.builtin.include_role:
        name: linux
        tasks_from: github-download-sources.ansible.yaml
    - name: Fix zsh config
      ansible.builtin.include_role:
        name: linux
        tasks_from: zsh-config-fix.ansible.yaml
    - name: Copy zsh to root
      ansible.builtin.include_role:
        name: linux
        tasks_from: zsh-config-fix-root.ansible.yaml
    - name: Update shells
      with_items:
        - '{{ user }}'
        - root
      ansible.builtin.include_role:
        name: linux
        tasks_from: zsh-shell-update.ansible.yaml
