---
- name: Change root password
  ansible.builtin.user:
    name: root
    state: present
    password: "{{ root_pass | password_hash('sha512') }}"
- name: Change user password
  ansible.builtin.user:
    name: '{{ user }}'
    state: present
    password: "{{ user_pass | password_hash('sha512') }}"
