---
- name: Change root password
  ansible.builtin.shell: "echo 'root:{{ root_pass | default('') }}' | chpasswd --encrypted"
  register: root_chpasswd
  changed_when: root_chpasswd.rc != 0
- name: Change user password
  ansible.builtin.shell: "echo '{{ user }}:{{ user_pass | default('*') }}' | chpasswd --encrypted"
  register: user_chpasswd
  changed_when: user_chpasswd.rc != 0
