---
# =================
# --- HOSTVARS ---
# =================
- name: Fix hostvars
  hosts: '{{ groups.nodes | default([]) }}'
  gather_facts: false
  tasks:
    - name: Fetch ssh key and use
      when: 'not skip_hostvars_fix_ssh_key_fetch | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: ssh-key-fetch-and-use.ansible.yaml
    - name: Add sudo to hostvars
      when: 'not skip_hostvars_fix_sudo | default(false)'
      ansible.builtin.include_role:
        name: vault
        tasks_from: sudo-password-add.ansible.yaml
# ================
# --- PLAYBOOK ---
# ================
- name: Uninstall longhorn
  hosts: '{{ groups.nodes | default([]) }}'
  become: true
  tasks:
    - name: Uninstall longhorn
      ansible.builtin.include_role:
        name: k8s
        tasks_from: longhorn-uninstall.ansible.yaml
