---
- name: Fetch ssh key
  delegate_to: localhost
  ansible.builtin.command: "op read 'op://{{ vault_id }}/{{ vault_node_hostname }}/public key'"
  register: ssh_key
  changed_when: ssh_key.rc != 0
- name: Add password to hostvars
  ansible.builtin.set_fact:
    ssh_key: '{{ ssh_key.stdout }}'
