---
- name: Get ssh password
  ansible.builtin.command: 'op read op://{{ vault_id }}/{{ user }}-{{ vault_node_hostname }}/password'
  delegate_to: localhost
  register: ssh_pass
  changed_when: ssh_pass.rc != 0
- name: Add password to hostvars
  ansible.builtin.set_fact:
    ansible_ssh_pass: '{{ ssh_pass.stdout }}'
