---
- name: Get ssh password
  ansible.builtin.command: 'op read op://Development/{{ user }}-{{ inventory_hostname }}/password'
  delegate_to: localhost
  register: ssh_pass
  changed_when: ssh_pass.rc != 0
- name: Add password to host_vars
  ansible.builtin.set_fact:
    ansible_ssh_pass: '{{ ssh_pass.stdout }}'
