---
- name: Get ts_key
  ansible.builtin.command: 'op read op://{{ vault_id }}/tokens/tailscale'
  delegate_to: localhost
  register: ts_key
  changed_when: ts_key.rc != 0
- name: Add ts_key to hostvars
  ansible.builtin.set_fact:
    ts_key: '{{ ts_key.stdout }}'
