---
- name: Get tskey
  ansible.builtin.command: 'op read op://{{ vault_id }}/tokens/tailscale'
  delegate_to: localhost
  register: tskey
  changed_when: tskey.rc != 0
- name: Add tskey to hostvars
  ansible.builtin.set_fact:
    tskey: '{{ tskey.stdout }}'
