---
- name: Get root password
  ansible.builtin.command: 'op read op://Development/root-{{ inventory_hostname }}/password'
  delegate_to: localhost
  register: root_pass
  changed_when: root_pass.rc != 0
- name: Get user password
  ansible.builtin.command: 'op read op://Development/{{ user }}-{{ inventory_hostname }}/password'
  delegate_to: localhost
  register: user_pass
  changed_when: user_pass.rc != 0
- name: Add passwords to hostvars
  ansible.builtin.set_fact:
    root_pass: '{{ root_pass.stdout }}'
    user_pass: '{{ user_pass.stdout }}'
